pull_request_rules:
  - name: automatic merge for Renovate pull requests
    conditions:
      - base=ci
      - author=renovate[bot]
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge