pull_request_rules:
  - name: automatic merge for Renovate pull requests
    conditions:
      - base=ci
      - author=renovate[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge