sudo: required

language: bash

branches:
  only:
  - ci

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make up

notifications:
  email:
    recipients:
      - sergiotm87@gmail.com
    on_success: always
    on_failure: always
